spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.190.247.157:3306/myplace?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Liu1234!
  server:
      port: 8080
      servlet:
        session:
          timeout: 30m #30分钟，测试的话时间不能太短，否则不准。m是分钟单位，s是秒的单位，h是小时的单位，不写单位的话默认是毫秒
  logging:
    config: classpath:logback-admin.xml
  log:
    level:
      root: info
      my: debug
    file: logs/admin-server.log
    maxsize: 30MB
  mvc:
    static-path-pattern: /**
mybatis:
  type-aliases-package: com.myplace.models.entity
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true